{% set name = "cosmosis-standalone" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76a9b78bde7b5331ff7cb92aeb9b2c5aed5aecb90c8347f0e031abc1b9059696
  patches:
    - setup.py-env-0000.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - python
    - {{ mpi }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - {{ mpi }}
    - liblapack
    - minuit2_standalone
  run:
    - python
    - {{ mpi }}
    - pyyaml
    - future
    - configparser
    - emcee
    - numpy
    - scipy
    - mpi4py
    - minuit2_standalone

test:
  imports:
    - cosmosis

about:
  home: https://bitbucket.org/joezuntz/cosmosis/src/master/
  license: BSD-2-Clause AND LicenseRef-non-commerical-use-only
  license_file: LICENSE
  summary: A stand-alone installation of the CosmoSIS project.

extra:
  recipe-maintainers:
    - beckermr
